export default [
    {message: 'Babla', dateStamp: Date.now(), user: 'Bob'},
    {message: 'Babla12312', dateStamp: Date.now() + 60000, user: 'C@ps Lock'},
    {message: 'Bablasdada asdasd g dsdg', dateStamp: Date.now() + 120000, user: 'Bob'},
    {message: 'Babla', dateStamp: Date.now(), user: 'Sleepyz'},
    {message: 'Babla12312', dateStamp: Date.now() + 60000, user: 'You'},
    {message: 'Bablasdada asdasd g dsdg', dateStamp: Date.now() + 120000, user: 'Bob'},
    {message: 'Babla', dateStamp: Date.now(), user: 'Me'},
    {message: 'Babla12312', dateStamp: Date.now() + 60000, user: 'You'},
    {message: 'Bablasdada asdasd g dsdg', dateStamp: Date.now() + 240000, user: 'Sleepyz'},
    {message: 'Babla', dateStamp: Date.now(), user: 'Me'},
    {message: 'Babla12312', dateStamp: Date.now() + 60000, user: 'You'},
    {message: 'Bablasdada asdasd g dsdg', dateStamp: Date.now() + 480000, user: 'Me'},
    {message: 'Babla', dateStamp: Date.now(), user: 'Me'},
    {message: 'Babla12312', dateStamp: Date.now() + 60000, user: 'You'},
    {message: 'Bablasdada asdasd g dsdg', dateStamp: Date.now() + 8160000, user: 'Me'},
]